name: tictactoe
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.0.0
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  uuid: ^3.0.7
  go_router: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
          weight: 900
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/Orbitron-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Orbitron-Regular.ttf
          weight: 400
